# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
	minecraft_version=1.21.11
	parchment_version=1.21.11
	parchment_snapshot=2025.12.20
	loader_version=0.18.2

# Mod Properties
	mod_version = 1.12.7
	maven_group = xyz.bluspring
	archives_base_name = Origins-Legacy

# Dependencies
	fabric_version=0.141.4+1.21.11
	cca_version=7.3.0
	clothconfig_version=21.11.151
	modmenu_version=17.0.0-alpha.1

# Publishing
	publishing.modrinth = mc1uvRn8
	publishing.curseforge = 1429195