# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
	minecraft_version=1.21.7
	parchment_version=1.21.6
	parchment_snapshot=2025.06.29
	loader_version=0.16.14

# Mod Properties
	mod_version = 1.10.5
	maven_group = xyz.bluspring
	archives_base_name = Origins-Legacy

# Dependencies
	fabric_version=0.128.2+1.21.7
	cca_version=7.0.0-beta.1
	clothconfig_version=19.0.147
	modmenu_version=15.0.0-beta.3

# Publishing
    publishing.modrinth = mc1uvRn8
    publishing.curseforge = 1429195