# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G

# Fabric Properties
	minecraft_version=26.1.2
	loader_version=0.18.5

# Mod Properties
	mod_version = 1.12.8
	maven_group = xyz.bluspring
	archives_base_name = Origins-Legacy

# Dependencies
	fabric_version=0.145.4+26.1.2
	cca_version=8.0.0
	clothconfig_version=26.1.154
	modmenu_version=18.0.0-alpha.8

# Publishing
	publishing.modrinth = mc1uvRn8
	publishing.curseforge = 1429195
	supported_versions = 26.1,26.1.1,26.1.2